package com.anzen.entities;
// Generated 27/05/2018 10:52:29 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Suceso generated by hbm2java
 */
@Entity
@Table(name = "suceso", catalog = "anzenjsf")
public class Suceso implements java.io.Serializable {

	private int id;
	private Tiposuceso tiposuceso;
	private Date fechaRegistro;
	private Date fechaSuceso;
	private String ubicacion;
	private String comentario;

	public Suceso() {
	}

	public Suceso(int id, Date fechaRegistro, Date fechaSuceso) {
		this.id = id;
		this.fechaRegistro = fechaRegistro;
		this.fechaSuceso = fechaSuceso;
	}

	public Suceso(int id, Tiposuceso tiposuceso, Date fechaRegistro, Date fechaSuceso, String ubicacion,
			String comentario) {
		this.id = id;
		this.tiposuceso = tiposuceso;
		this.fechaRegistro = fechaRegistro;
		this.fechaSuceso = fechaSuceso;
		this.ubicacion = ubicacion;
		this.comentario = comentario;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_suceso")
	public Tiposuceso getTiposuceso() {
		return this.tiposuceso;
	}

	public void setTiposuceso(Tiposuceso tiposuceso) {
		this.tiposuceso = tiposuceso;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_registro", nullable = false, length = 10)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_suceso", nullable = false, length = 10)
	public Date getFechaSuceso() {
		return this.fechaSuceso;
	}

	public void setFechaSuceso(Date fechaSuceso) {
		this.fechaSuceso = fechaSuceso;
	}

	@Column(name = "ubicacion", length = 250)
	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	@Column(name = "comentario", length = 300)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

}
