package com.anzen.entities;
// Generated 27/05/2018 10:52:29 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tiposuceso generated by hbm2java
 */
@Entity
@Table(name = "tiposuceso", catalog = "anzenjsf", uniqueConstraints = @UniqueConstraint(columnNames = "tipo"))
public class Tiposuceso implements java.io.Serializable {

	private int id;
	private String tipo;
	private Set<Suceso> sucesos = new HashSet<Suceso>(0);

	public Tiposuceso() {
	}

	public Tiposuceso(int id, String tipo) {
		this.id = id;
		this.tipo = tipo;
	}

	public Tiposuceso(int id, String tipo, Set<Suceso> sucesos) {
		this.id = id;
		this.tipo = tipo;
		this.sucesos = sucesos;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "tipo", unique = true, nullable = false, length = 50)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tiposuceso")
	public Set<Suceso> getSucesos() {
		return this.sucesos;
	}

	public void setSucesos(Set<Suceso> sucesos) {
		this.sucesos = sucesos;
	}

}
